- src/app/components/shared/attachment-list/AttachmentList.js
- src/app/components/shared/attachment-list/attachmentList.less
> Style changes to attachment list

- package.json
> Updated nav icons

- src/app/components/shared/dialog-box/DialogBox.js
- src/app/components/shared/dialog-box/dialogBox.less
> Mergefixes for DialogBox component

- src/app/components/shared/stepper/stepper.less
> Increased margin between stepper buttons

- src/app/components/engangsstonad/steps/Engangsstonad.step3.js
> Revamped engangsstonad step 3

- src/app/components/shared/country-picker/CountryPicker.js
- src/app/components/shared/country-picker/countryPicker.less
> New component CountryPicker

- Jenkinsfile
> added npm path in Jenkinsfile

- Jenkinsfile
> added full path for npm in Jenkinsfile

- Jenkinsfile
- nais.yml
- nginx.conf
> Jenkinsfile

- src/app/bootstrap.js
- src/app/components/engangsstonad/Engangsstonad.index.js
- src/app/components/error/index.js
- src/app/components/shared/stepper/Stepper.js
- src/app/components/shared/stepper/stepper.less
- src/app/util/routing/index.js
- src/app/util/routing/routes.config.js
- src/app/util/routing/routes.js
- src/config/webpack.dev.js
> Opprydning i routing + enkel 404-side + link implementert som knapp

- src/app/bootstrap.js
- src/app/components/engangsstonad/Engangsstonad.index.spec.js
- src/app/util/routing/index.js
> Fixed test failing due to missing webpack require.context

- src/app/components/shared/checkbox-with-line/CheckboxWithLine.js
- src/app/components/shared/date-input/DateInput.js
- src/app/components/shared/display-text-with-label/DisplayTextWithLabel.js
- src/app/components/shared/icon-with-text/IconWithText.js
- src/app/components/shared/opplysning-panel/OpplysningPanel.js
- src/app/components/shared/radio-group/RadioGroup.js
- src/app/components/shared/text-with-label/DisplayTextWithLabel.js
> Remove flow

- mocha.opts
- package.json
- src/app/components/engangsstonad/Engangsstonad.index.js
- src/app/components/engangsstonad/Engangsstonad.index.spec.js
> Fixed failing tests after previous merge to master

- src/app/components/engangsstonad/Engangsstonad.index.spec.js
- src/app/components/engangsstonad/steps/Engangsstonad.step1.js
- src/app/components/engangsstonad/steps/Engangsstonad.step2.js
- src/app/components/engangsstonad/steps/Engangsstonad.step3.js
- src/app/components/engangsstonad/steps/Engangsstonad.step4.js
- src/app/components/shared/stepper/Stepper.spec.js
- src/config/webpack.dev.js
> Fikset linting-warnings og noe refaktorering

- package.json
- src/app/components/engangsstonad/steps/Engangsstonad.step1.js
- src/app/components/engangsstonad/steps/Engangsstonad.step2.js
- src/app/components/engangsstonad/steps/Engangsstonad.step3.js
- src/app/components/engangsstonad/steps/Engangsstonad.step4.js
> Bruke react-document-title for å sette sidetittel i nettleser

- tsconfig.json
> Added support for webpack alias to VS Code settings

- src/app/components/engangsstonad/steps/Engangsstonad.step2.js
- src/app/components/engangsstonad/steps/engangsstonad.step2.less
- src/app/components/shared/attachment-button/AttachmentButton.js
- src/app/components/shared/dialog-box/DialogBox.js
- src/app/components/shared/dialog-box/dialogBox.less
- src/app/components/shared/icon-link/IconLink.js
- src/app/components/shared/icon-link/iconLink.less
> Dialog box changes

- .eslintrc
- src/app/components/engangsstonad/steps/Engangsstonad.step2.js
- src/app/components/shared/date-input/DateInput.js
- src/app/components/shared/date-input/dayPicker.less
> A little housekeeping

- src/app/components/shared/stepper/Stepper.js
> Changed stepper button types

- src/app/components/engangsstonad/steps/EngangsstonadStep3.js
> fix variable names

- .env
- .gitignore
- package.json
- src/app/api/index.js
- src/build/webpack/devserver.config.js
- src/build/webpack/webpack.config.dev.js
> Fixed double /rest in url + cleanup

- package.json
- src/app/components/engangsstonad/EngangsstonadConfirmation.js
- src/app/components/engangsstonad/steps/EngangsstonadStep2.js
- src/app/components/engangsstonad/steps/EngangsstonadStep3.js
- src/app/components/intl/nb_NO.json
- src/app/components/intl/nn_NO.json
- src/app/components/shared/country-picker/CountryList.js
- src/app/components/shared/country-picker/CountryListElement.js
- src/app/components/shared/country-picker/CountryListSummaryElement.js
- src/app/components/shared/country-picker/CountryModal.js
- src/app/components/shared/country-picker/CountryPicker.js
- src/app/components/shared/country-picker/countryPicker.less
- src/app/components/shared/dialog-box/dialogBox.less
- src/app/index.html
> Add ISO codes to country-picker and new design

- server.js
- src/build/webpack/devserver.config.js
- src/build/webpack/webpack.config.global.js
> Set context root to /engangsstonad
